@startuml
start
:Remove specified element data;
if (Is main element present?) then (yes)
  :Extract "main element";
else (no)
  if (Is article element present?) then (yes)
    :Extract "article element";
  else (no)
    :Get element ID "contents" or "main" deepest level element data;
    if (Is deepest level element present?) then (yes)
      :Extract "deepest element_data";
    else (no)
      :Extract using Trafilatura;
      :Execute trafilatura.extract;
    endif
  endif
endif
stop
@enduml